---

version: '2'
services:
  app:
    build: .
    environment:
       - MAIL_USERNAME
       - MAIL_PASSWORD
       - MAIL_DEFAULT_SENDER
       - MAIL_SERVER
       - MAIL_PORT
       - MAIL_USE_SSL
       - MYSQL_USER
       - MYSQL_DATABASE
       - MYSQL_PASSWORD
   links:
       - "mysql"
  nginx:
    build: nginx/
    ports: 
       - "8000:80"
    links:
       - "app"
    environment:
       - "SITE=localhost:8000"
  mysql:
    image: mysql
    environment:
       - MYSQL_ROOT_PASSWORD
       - MYSQL_DATABASE
       - MYSQL_PASSWORD
       - MYSQL_USER
